package composegen

import (
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"
)

var genLineRE = regexp.MustCompile(`(?m)^# Generated: .*$`)

// normalize masks the one non-deterministic line (the generation timestamp) so
// Go output can be compared byte-for-byte against the bash reference.
func normalize(s string) string {
	return genLineRE.ReplaceAllString(s, "# Generated: <timestamp>")
}

// TestParity is the core acceptance test for 6.5a: for each testdata case, the
// Go generator must produce output byte-identical to scripts/compose-gen.sh
// (the expected.yml files were generated by the real bash script). Cases cover
// custom stacks (postgres/redis, Traefik on/off), the full custom matrix
// (mysql + garage + frontend + nodejs + swarm + SSL), and the image stack
// (depends_on, named volumes, env_vars, ports/expose, healthcheck, overrides).
func TestParity(t *testing.T) {
	base := filepath.Join("testdata", "cases")
	entries, err := os.ReadDir(base)
	if err != nil {
		t.Fatalf("read cases: %v", err)
	}
	fixed := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		t.Run(name, func(t *testing.T) {
			dir := filepath.Join(base, name)
			cfg, err := os.ReadFile(filepath.Join(dir, "config.json"))
			if err != nil {
				t.Fatal(err)
			}
			envBytes, err := os.ReadFile(filepath.Join(dir, "env.txt"))
			if err != nil {
				t.Fatal(err)
			}
			env := strings.TrimSpace(string(envBytes))
			expected, err := os.ReadFile(filepath.Join(dir, "expected.yml"))
			if err != nil {
				t.Fatal(err)
			}

			got, err := GenerateAt(cfg, env, fixed)
			if err != nil {
				t.Fatalf("generate: %v", err)
			}

			gotN := normalize(string(got))
			expN := normalize(string(expected))
			if gotN != expN {
				t.Errorf("parity mismatch (%s/%s):\n%s", name, env, firstDiff(expN, gotN))
			}
		})
	}
}

// firstDiff returns a human-readable description of the first differing lines.
func firstDiff(want, got string) string {
	wl := strings.Split(want, "\n")
	gl := strings.Split(got, "\n")
	n := len(wl)
	if len(gl) > n {
		n = len(gl)
	}
	var b strings.Builder
	shown := 0
	for i := 0; i < n && shown < 12; i++ {
		var w, g string
		if i < len(wl) {
			w = wl[i]
		}
		if i < len(gl) {
			g = gl[i]
		}
		if w != g {
			b.WriteString("  line " + itoa(i+1) + ":\n")
			b.WriteString("    bash: " + quote(w) + "\n")
			b.WriteString("    go  : " + quote(g) + "\n")
			shown++
		}
	}
	if shown == 0 {
		b.WriteString("  (length differs: bash=" + itoa(len(wl)) + " go=" + itoa(len(gl)) + " lines)\n")
	}
	return b.String()
}

func quote(s string) string  { return "\"" + s + "\"" }
func itoa(i int) string      { return strconv.Itoa(i) }

// TestHealthcheckQuoteEscaping guards the historical YAML bug: literal double
// quotes in a healthcheck command must be escaped so the flow sequence stays valid.
func TestHealthcheckQuoteEscaping(t *testing.T) {
	cfg := []byte(`{
		"project": {"name":"q","type":"image","version":{"major":1,"minor":0,"patch":0,"build":0}},
		"images": [{"name":"web","image":"nginx","tag":"alpine","port":80,
			"healthcheck":"sh -c \"curl -sf http://localhost/ || exit 1\""}],
		"environments": {"dev": {"deployment":"compose"}}
	}`)
	out, err := GenerateAt(cfg, "dev", time.Unix(0, 0).UTC())
	if err != nil {
		t.Fatal(err)
	}
	want := `      test: ["CMD-SHELL", "sh -c \"curl -sf http://localhost/ || exit 1\""]`
	if !strings.Contains(string(out), want) {
		t.Errorf("healthcheck quotes not escaped.\nwant line: %s\ngot:\n%s", want, out)
	}
}
