package maintenance

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultDynamicDir is the Traefik file-provider directory (same volume the ACME
// issuer writes to). Overridable via RIGGER_DYNAMIC_DIR for tests/dev.
const DefaultDynamicDir = "/dynamic"

// DynDir returns the file-provider directory rigger writes maintenance fragments to.
func DynDir() string {
	if d := strings.TrimSpace(os.Getenv("RIGGER_DYNAMIC_DIR")); d != "" {
		return d
	}
	return DefaultDynamicDir
}

// sanitize turns ws/project/env into a Traefik-safe id segment (alnum + hyphen).
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	return b.String()
}

// id is the per-env router/middleware id (and fragment basename), unique per env.
func id(ws, project, env string) string {
	return "maint-" + sanitize(ws) + "-" + sanitize(project) + "-" + sanitize(env)
}

// fragmentPath is the file-provider YAML for an env's maintenance routers.
func fragmentPath(dir, ws, project, env string) string {
	return filepath.Join(dir, id(ws, project, env)+".yml")
}

// SeedServiceYAML is the shared file-provider service all per-env maintenance routers
// point at: the always-on rigger UI container, which renders the maintenance page.
// Written once at boot (see cmd/server seedMaintenanceService), like rigger-loading.yml.
const SeedServiceYAML = `# Auto-generated by Rigger on boot — do not edit.
# Shared service for maintenance-mode routers: the always-on rigger UI renders the
# "under maintenance" page (per-env maintenance routers reference rigger-maint@file).
http:
  services:
    rigger-maint:
      loadBalancer:
        servers:
          - url: "http://rigger:8080"
`

// Apply writes the file-provider fragment that routes the env's host(s) to the
// maintenance page. hosts are the bare Host() values (no scheme); ssl adds a
// websecure router (Traefik serves the env's existing SNI cert). Every request path
// is rewritten to /maintenance/{ws}/{project}/{env} so rigger renders the right page.
// Returns an error when no host can be matched.
func Apply(dir, ws, project, env string, hosts []string, ssl bool) error {
	var clean []string
	seen := map[string]bool{}
	for _, h := range hosts {
		h = strings.TrimSpace(h)
		if h == "" || seen[h] {
			continue
		}
		seen[h] = true
		clean = append(clean, h)
	}
	if len(clean) == 0 {
		return fmt.Errorf("maintenance: no host to route (env not web-routed?)")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("maintenance: ensure %s: %w", dir, err)
	}
	rid := id(ws, project, env)
	rule := make([]string, len(clean))
	for i, h := range clean {
		rule[i] = "Host(`" + h + "`)"
	}
	ruleStr := strings.Join(rule, " || ")
	rewrite := "/maintenance/" + ws + "/" + project + "/" + env

	var b strings.Builder
	fmt.Fprintf(&b, "# Auto-generated by Rigger — maintenance mode for %s/%s/%s. Do not edit.\n", ws, project, env)
	b.WriteString("http:\n  routers:\n")
	writeRouter := func(name, entry string, tls bool) {
		fmt.Fprintf(&b, "    %s:\n", name)
		fmt.Fprintf(&b, "      rule: %q\n", ruleStr)
		b.WriteString("      priority: 100000\n")
		fmt.Fprintf(&b, "      entryPoints: [\"%s\"]\n", entry)
		b.WriteString("      service: rigger-maint@file\n")
		fmt.Fprintf(&b, "      middlewares: [\"%s-rw\"]\n", rid)
		if tls {
			b.WriteString("      tls: {}\n")
		}
	}
	writeRouter(rid, "web", false)
	if ssl {
		writeRouter(rid+"-secure", "websecure", true)
	}
	b.WriteString("  middlewares:\n")
	fmt.Fprintf(&b, "    %s-rw:\n", rid)
	b.WriteString("      replacePathRegex:\n")
	b.WriteString("        regex: \"^/.*\"\n")
	fmt.Fprintf(&b, "        replacement: %q\n", rewrite)

	if err := os.WriteFile(fragmentPath(dir, ws, project, env), []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("maintenance: write fragment: %w", err)
	}
	return nil
}

// Clear removes an env's maintenance fragment (no-op if absent).
func Clear(dir, ws, project, env string) error {
	err := os.Remove(fragmentPath(dir, ws, project, env))
	if err != nil && os.IsNotExist(err) {
		return nil
	}
	return err
}

// Exists reports whether an env's maintenance fragment is currently written.
func Exists(dir, ws, project, env string) bool {
	_, err := os.Stat(fragmentPath(dir, ws, project, env))
	return err == nil
}
