package proxyroutes

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Per-env INLINE access middlewares: an env that doesn't attach a reusable workspace Access List
// can still set its own IP allow-list, GeoIP country policy, and a "block common exploits"
// hardening header set directly on the env. These are rendered ONCE per env into the file
// provider as `appmw-<ws>-<proj>-<env>-{ipallow,geo,sec}` and attached to the env's app routers
// by composegen via `name@file` — the same cross-provider bridge the shared ACLs use. Inline
// IP/Geo apply only when NO access list is attached (the list owns those); block-exploits applies
// in every mode. See docs/design/workspace-plugins-and-access-lists.md.

// envMWChar keeps only file/middleware-name-safe characters (lowercase letter, digit, dash).
func envMWChar(r rune) rune {
	switch {
	case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
		return r
	case r >= 'A' && r <= 'Z':
		return r + 32
	default:
		return '-'
	}
}

// envPrefix is the middleware / file basename for an env's inline middlewares.
func envPrefix(workspace, project, env string) string {
	return strings.Map(envMWChar, "appmw-"+workspace+"-"+project+"-"+env)
}

// splitList tokenizes a comma / space / newline separated field (CIDRs, country codes).
func splitList(s string) []string {
	repl := strings.NewReplacer(",", " ", "\n", " ", "\t", " ")
	return strings.Fields(repl.Replace(s))
}

// writeExploitsMiddleware emits the plugin-free "block common exploits" middleware: baseline
// hardening response headers (clickjacking, MIME-sniffing, XSS, referrer). Request-pattern
// filtering (SQLi / path traversal) needs the WAF plugin — that's the separate WAF toggle.
func writeExploitsMiddleware(b *strings.Builder, prefix string) {
	fmt.Fprintf(b, "    %s-sec:\n      headers:\n", prefix)
	b.WriteString("        frameDeny: true\n")
	b.WriteString("        contentTypeNosniff: true\n")
	b.WriteString("        browserXssFilter: true\n")
	b.WriteString("        referrerPolicy: \"strict-origin-when-cross-origin\"\n")
}

// RenderEnvMiddlewares (re)writes /dynamic/appmw-<ws>-<proj>-<env>.yml from the env's inline
// access config and returns the `name@file` refs composegen should attach to its app routers.
// Inline IP/Geo are skipped when the env attaches an access list (the list owns them);
// block-exploits always applies. Writes nothing and prunes any stale fragment when there's
// nothing enforceable. Best-effort: returns (nil, nil) when the config can't be parsed or the
// env is absent. geoEnabled gates geoblock emission (the GeoIP plugin must be enabled).
func RenderEnvMiddlewares(dir, workspace, project, env string, configBytes []byte, geoEnabled bool) ([]string, error) {
	prefix := envPrefix(workspace, project, env)
	path := filepath.Join(dir, prefix+".yml")
	prune := func() ([]string, error) { _ = os.Remove(path); return nil, nil }

	var cfg struct {
		Environments map[string]envAttach `json:"environments"`
	}
	if err := json.Unmarshal(configBytes, &cfg); err != nil {
		return prune()
	}
	a, ok := cfg.Environments[env]
	if !ok {
		return prune()
	}

	var cidrs, countries []string
	geoMode := ""
	if a.AccessListID == 0 { // inline IP/Geo apply only when no access list is attached
		if a.IPMode == "allow" {
			cidrs = splitList(a.IPCIDRs)
		}
		if a.GeoMode == "allow" || a.GeoMode == "block" {
			geoMode = a.GeoMode
			for _, c := range splitList(a.GeoCountries) {
				countries = append(countries, strings.ToUpper(c))
			}
		}
	}

	var mw strings.Builder
	// users=nil: per-env basic-auth is the separate auth-gate path (APP_AUTH_*), not inline here.
	names := writeAccessMiddlewares(&mw, prefix, nil, true, cidrs, geoMode, countries, geoEnabled)
	if a.BlockExploits {
		writeExploitsMiddleware(&mw, prefix)
		names = append(names, prefix+"-sec")
	}
	if len(names) == 0 {
		return prune()
	}

	var doc strings.Builder
	fmt.Fprintf(&doc, "# Auto-generated by Rigger (inline app access for %s/%s/%s). Do not edit.\n", workspace, project, env)
	doc.WriteString("http:\n  middlewares:\n")
	doc.WriteString(mw.String())
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, []byte(doc.String()), 0o644); err != nil {
		return nil, fmt.Errorf("proxyroutes: write env middlewares %s: %w", prefix, err)
	}
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = n + "@file"
	}
	return out, nil
}
