package proxyroutes

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/mansoor/rigger/ui/internal/crypto"
	"github.com/mansoor/rigger/ui/internal/db"
)

// DefaultDynamicDir is Traefik's file-provider directory (the shared rigger-dynamic
// volume, mounted rw in rigger). Overridable via RIGGER_DYNAMIC_DIR for tests/dev.
const DefaultDynamicDir = "/dynamic"

// DynDir returns the file-provider directory rigger writes proxy fragments to.
func DynDir() string {
	if d := strings.TrimSpace(os.Getenv("RIGGER_DYNAMIC_DIR")); d != "" {
		return d
	}
	return DefaultDynamicDir
}

// riggerSink is the in-network rigger UI service every redirect/default-status router
// points at (the redirect middleware short-circuits before it; the default-status
// router has rigger return the chosen code). Defined once in proxy-base.yml.
const riggerSink = "proxy-rigger@file"

// baseYAML builds the always-present shared config: the rigger sink service, plus the
// WAF/cache plugin MIDDLEWARE instances when those plugins are enabled instance-wide.
// The plugin instances require the matching plugin to be declared in Traefik's static
// command (see src/docker-compose.yml) — enabling the flag without that makes opted-in
// routers error (a one-time, deliberate operator step; see docs/design/proxy-service.md).
func baseYAML(wafEnabled, cacheEnabled bool) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by Rigger (Proxy Service) — do not edit.\n")
	b.WriteString("http:\n  services:\n    proxy-rigger:\n      loadBalancer:\n        servers:\n          - url: \"http://rigger:8080\"\n")
	if wafEnabled || cacheEnabled {
		b.WriteString("  middlewares:\n")
		if wafEnabled {
			// Coraza (OWASP CRS) WAF plugin instance. Plugin name "coraza" must match the
			// experimental.plugins.coraza declaration in Traefik's static command.
			b.WriteString("    proxy-waf:\n      plugin:\n        coraza:\n          directives: |\n            Include @coraza.conf-recommended\n            Include @crs-setup.conf.example\n            Include @owasp_crs/*.conf\n            SecRuleEngine On\n")
		}
		if cacheEnabled {
			// Souin HTTP-cache plugin instance (defaults; GET/HEAD). Plugin name "souin"
			// must match the experimental.plugins.souin declaration in Traefik's command.
			b.WriteString("    proxy-cache:\n      plugin:\n        souin: {}\n")
		}
	}
	return b.String()
}

// rid is a route's Traefik id / fragment basename.
func rid(id int64) string { return "proxy-" + strconv.FormatInt(id, 10) }

func fragPath(dir string, id int64) string { return filepath.Join(dir, rid(id)+".yml") }
func certPath(dir string, id int64) string { return filepath.Join(dir, "secrets", rid(id)+".crt") }
func keyPath(dir string, id int64) string  { return filepath.Join(dir, "secrets", rid(id)+".key") }

// Render rebuilds the file-provider config for all routes: it writes proxy-base.yml +
// one proxy-<id>.yml per enabled route, then removes any stale proxy-*.yml. waf/cache
// middleware refs are emitted only when that plugin is enabled instance-wide (PX-6).
func Render(d *db.DB, dir string, cryptoKey []byte, wafEnabled, cacheEnabled, geoEnabled bool) error {
	st := NewStore(d)
	routes, err := st.List()
	if err != nil {
		return err
	}
	lists, err := st.AccessListMap()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("proxyroutes: ensure %s: %w", dir, err)
	}
	want := map[string]bool{"proxy-base.yml": true}
	if err := os.WriteFile(filepath.Join(dir, "proxy-base.yml"), []byte(baseYAML(wafEnabled, cacheEnabled)), 0o644); err != nil {
		return fmt.Errorf("proxyroutes: write base: %w", err)
	}
	for _, r := range routes {
		if !r.Enabled {
			continue
		}
		yaml, err := routeYAML(r, dir, cryptoKey, wafEnabled, cacheEnabled, geoEnabled, lists)
		if err != nil {
			return fmt.Errorf("proxyroutes: render route %d (%s): %w", r.ID, r.Name, err)
		}
		if yaml == "" {
			continue // e.g. default route in "page" mode emits nothing (built-in fallback handles it)
		}
		if err := os.WriteFile(fragPath(dir, r.ID), []byte(yaml), 0o644); err != nil {
			return fmt.Errorf("proxyroutes: write route %d: %w", r.ID, err)
		}
		want[rid(r.ID)+".yml"] = true
	}
	// Remove stale fragments (disabled/deleted routes) — anything proxy-*.yml not wanted.
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		n := e.Name()
		if strings.HasPrefix(n, "proxy-") && strings.HasSuffix(n, ".yml") && !want[n] {
			_ = os.Remove(filepath.Join(dir, n))
		}
	}
	return nil
}

// effectiveAccess resolves a route's auth users / pass-auth / IP allow CIDRs / GeoIP
// policy: from the referenced access list when one is set (and exists), else from the
// route's own inline fields. Traefik's ipAllowList is allow-only, so only "allow" rules
// become a sourceRange. GeoIP is access-list-only (no inline equivalent).
func effectiveAccess(r Route, lists map[int64]AccessList) (users []BasicUser, passAuth bool, cidrs []string, geoMode string, countries []string) {
	passAuth = true
	geoMode = "off"
	if r.AccessListID > 0 {
		// Strict isolation: a global Proxy Service route only ever applies a GLOBAL access
		// list (al.Workspace == ""). A workspace list id (which the UI no longer offers here)
		// is ignored — the route falls through to its inline config rather than reaching
		// across the tenant boundary. See docs/design/workspace-plugins-and-access-lists.md.
		if al, ok := lists[r.AccessListID]; ok && al.Workspace == "" {
			passAuth = al.PassAuth
			users = al.Users
			cidrs = allowCIDRs(al.Rules)
			if al.GeoMode == "allow" || al.GeoMode == "block" {
				geoMode = al.GeoMode
				countries = al.Countries
			}
			return users, passAuth, cidrs, geoMode, countries
		}
		// referenced list missing or out-of-scope — fall through to inline (defensive)
	}
	if r.AuthMode == "basic" {
		users = r.AuthUsers
	}
	cidrs = splitCSV(r.IPAllow)
	if r.GeoMode == "allow" || r.GeoMode == "block" {
		geoMode = r.GeoMode
		countries = r.Countries
	}
	return users, passAuth, cidrs, geoMode, countries
}

// geoDBPath is where the GeoIP database is expected inside the Traefik container. Mount
// an IP2Location LITE BIN DB here (see docker-compose.yml + docs/design/proxy-service.md).
const geoDBPath = "/geoip/IP2LOCATION-LITE-DB1.IPV6.BIN"

// geoMiddleware emits an nscuro/traefik-plugin-geoblock instance for one route. mode is
// "allow" (only the listed countries) or "block" (everything except the listed). The
// plugin name "geoblock" must match the experimental.plugins.geoblock static declaration.
func geoMiddleware(b *strings.Builder, id, mode string, countries []string) {
	fmt.Fprintf(b, "    %s-geo:\n      plugin:\n        geoblock:\n", id)
	b.WriteString("          enabled: true\n")
	fmt.Fprintf(b, "          databaseFilePath: %q\n", geoDBPath)
	b.WriteString("          allowPrivate: true\n")
	b.WriteString("          disallowedStatusCode: 403\n")
	key := "allowedCountries"
	if mode == "block" {
		key = "blockedCountries"
		b.WriteString("          defaultAllow: true\n")
	} else {
		b.WriteString("          defaultAllow: false\n")
	}
	fmt.Fprintf(b, "          %s:\n", key)
	for _, c := range countries {
		fmt.Fprintf(b, "            - %q\n", c)
	}
}

// writeAccessMiddlewares emits basicAuth / ipAllowList / geoblock middleware definitions under
// the given name prefix and returns the middleware names (in chain order). Shared by per-route
// proxy rendering (prefix "proxy-<id>") and the workspace shared-ACL renderer (prefix
// "acl-<ws>-<id>"). Geo is emitted only when the plugin is enabled instance-wide.
func writeAccessMiddlewares(b *strings.Builder, prefix string, users []BasicUser, passAuth bool, cidrs []string, geoMode string, countries []string, geoEnabled bool) []string {
	var names []string
	if len(users) > 0 {
		fmt.Fprintf(b, "    %s-auth:\n      basicAuth:\n", prefix)
		if !passAuth {
			b.WriteString("        removeHeader: true\n")
		}
		b.WriteString("        users:\n")
		for _, u := range users {
			fmt.Fprintf(b, "          - %q\n", u.User+":"+u.Hash)
		}
		names = append(names, prefix+"-auth")
	}
	if len(cidrs) > 0 {
		fmt.Fprintf(b, "    %s-ipallow:\n      ipAllowList:\n        sourceRange:\n", prefix)
		for _, c := range cidrs {
			fmt.Fprintf(b, "          - %q\n", c)
		}
		names = append(names, prefix+"-ipallow")
	}
	if geoEnabled && (geoMode == "allow" || geoMode == "block") && len(countries) > 0 {
		geoMiddleware(b, prefix, geoMode, countries)
		names = append(names, prefix+"-geo")
	}
	return names
}

// routeYAML renders the file-provider YAML for one enabled route. Returns "" when the
// route emits nothing (default route in page mode).
func routeYAML(r Route, dir string, cryptoKey []byte, wafEnabled, cacheEnabled, geoEnabled bool, lists map[int64]AccessList) (string, error) {
	id := rid(r.ID)
	tlsOn := r.TLSMode != "" && r.TLSMode != "none"
	entry := "web"
	if tlsOn {
		entry = "websecure"
	}

	// Build the matching rule.
	rule, priority := routeRule(r)
	if rule == "" {
		return "", nil // default route, page mode → nothing to emit
	}

	var routers, services, middlewares, transports, tlsCerts strings.Builder
	var mws []string // middleware refs for the main router, in order

	// ── Redirect-scheme (force HTTPS) lives on a separate web→websecure router below;
	//    here we collect content middlewares applied to the main (serving) router. ──
	// Auth + IP + GeoIP come from the route's access list when set, else inline fields.
	authUsers, passAuth, ipCIDRs, geoMode, geoCountries := effectiveAccess(r, lists)
	mws = append(mws, writeAccessMiddlewares(&middlewares, id, authUsers, passAuth, ipCIDRs, geoMode, geoCountries, geoEnabled)...)
	if hdr := headersMiddleware(id, r); hdr != "" {
		middlewares.WriteString(hdr)
		mws = append(mws, id+"-headers")
	}
	if r.StripPrefix && r.PathPrefix != "" {
		fmt.Fprintf(&middlewares, "    %s-strip:\n      stripPrefix:\n        prefixes:\n          - %q\n", id, r.PathPrefix)
		mws = append(mws, id+"-strip")
	}
	// Plugin middlewares (only when enabled instance-wide; the definitions live in
	// proxy-base.yml under PX-6). Referencing a missing middleware would break the router.
	if r.WAF && wafEnabled {
		mws = append(mws, "proxy-waf@file")
	}
	if r.Cache && cacheEnabled {
		mws = append(mws, "proxy-cache@file")
	}

	// ── Service + router by route kind ──
	isRedirectKind := r.Type == "redirect" || (r.IsDefault && r.DefaultMode == "redirect")
	isStatusKind := r.IsDefault && (r.DefaultMode == "404" || r.DefaultMode == "403" || r.DefaultMode == "close")

	switch {
	case isRedirectKind:
		// Redirect: middleware short-circuits to the target; service is the rigger sink
		// (required by the schema, never actually forwarded to).
		target := strings.TrimSpace(r.RedirectTo)
		if target == "" {
			return "", fmt.Errorf("redirect route needs a target URL")
		}
		permanent := r.RedirectCode != 302
		fmt.Fprintf(&middlewares, "    %s-redirect:\n      redirectRegex:\n        regex: \"^.*$\"\n        replacement: %q\n        permanent: %t\n", id, target, permanent)
		writeRouter(&routers, id, rule, entry, riggerSink, append([]string{id + "-redirect"}, mws...), tlsOn, r, priority)

	case isStatusKind:
		// Default catch-all returning a bare status: route to rigger, which serves the
		// status at /__proxydefault/<mode> (see PX-4 rigger-fallback handling).
		fmt.Fprintf(&middlewares, "    %s-status:\n      replacePath:\n        path: %q\n", id, "/__proxydefault/"+r.DefaultMode)
		writeRouter(&routers, id, rule, entry, riggerSink, append([]string{id + "-status"}, mws...), tlsOn, r, priority)

	default:
		// Proxy (normal or default-proxy): load-balance to the upstreams.
		if len(r.Upstreams) == 0 {
			return "", fmt.Errorf("proxy route needs at least one upstream")
		}
		fmt.Fprintf(&services, "    %s:\n      loadBalancer:\n", id)
		fmt.Fprintf(&services, "        passHostHeader: %t\n", r.PassHostHeader)
		services.WriteString("        servers:\n")
		for _, u := range r.Upstreams {
			fmt.Fprintf(&services, "          - url: %q\n", upstreamURL(u))
		}
		if r.InsecureSkipVerify {
			fmt.Fprintf(&services, "        serversTransport: %s-transport\n", id)
			fmt.Fprintf(&transports, "    %s-transport:\n      insecureSkipVerify: true\n", id)
		}
		writeRouter(&routers, id, rule, entry, id, mws, tlsOn, r, priority)
	}

	// ── custom locations: each path → its own upstream (NPM "Custom locations") ──
	// More-specific (Host && PathPrefix) so they win over the base host router; they
	// inherit the route's middlewares + TLS. Only for normal proxy routes.
	if !isRedirectKind && !isStatusKind && !r.IsDefault {
		hosts := hostsExpr(r.Host)
		for n, loc := range r.Locations {
			servers := loc.Servers()
			if strings.TrimSpace(loc.Path) == "" || len(servers) == 0 {
				continue
			}
			lid := fmt.Sprintf("%s-loc%d", id, n)
			lmws := append([]string{}, mws...)
			if fp := strings.TrimSpace(loc.ForwardPath); fp != "" {
				// nginx proxy_pass-style: strip the location path, prepend the upstream sub-path.
				fmt.Fprintf(&middlewares, "    %s-rw:\n      replacePathRegex:\n        regex: %q\n        replacement: %q\n",
					lid, "^"+regexp.QuoteMeta(loc.Path)+"(/.*)?$", strings.TrimRight(fp, "/")+"$1")
				lmws = append([]string{lid + "-rw"}, lmws...)
			}
			fmt.Fprintf(&services, "    %s:\n      loadBalancer:\n        passHostHeader: %t\n        servers:\n", lid, r.PassHostHeader)
			for _, u := range servers {
				fmt.Fprintf(&services, "          - url: %q\n", upstreamURL(u))
			}
			if r.InsecureSkipVerify {
				fmt.Fprintf(&services, "        serversTransport: %s-transport\n", lid)
				fmt.Fprintf(&transports, "    %s-transport:\n      insecureSkipVerify: true\n", lid)
			}
			writeRouter(&routers, lid, combineRule(hosts, loc.Path), entry, lid, lmws, tlsOn, r, 100)
		}
	}

	// ── force-HTTPS: an extra web→websecure redirect router (per-router, not global) ──
	if tlsOn && r.ForceHTTPS {
		middlewares.WriteString("    " + id + "-tohttps:\n      redirectScheme:\n        scheme: https\n        permanent: true\n")
		fmt.Fprintf(&routers, "    %s-http:\n      rule: %q\n      entryPoints: [\"web\"]\n      service: %s\n      middlewares: [%q]\n", id, rule, riggerSink, id+"-tohttps")
		if priority > 0 {
			fmt.Fprintf(&routers, "      priority: %d\n", priority)
		}
	}

	// ── custom cert: write cert/key to /dynamic/secrets and register via tls.certificates ──
	if r.TLSMode == "custom" {
		if err := os.MkdirAll(filepath.Join(dir, "secrets"), 0o700); err != nil {
			return "", err
		}
		if strings.TrimSpace(r.TLSCertPEM) == "" || r.TLSKeyEnc == "" {
			return "", fmt.Errorf("custom TLS needs both a certificate and a key")
		}
		keyPEM, err := crypto.Decrypt(cryptoKey, r.TLSKeyEnc)
		if err != nil {
			return "", fmt.Errorf("decrypt TLS key: %w", err)
		}
		if err := os.WriteFile(certPath(dir, r.ID), []byte(r.TLSCertPEM), 0o644); err != nil {
			return "", err
		}
		if err := os.WriteFile(keyPath(dir, r.ID), keyPEM, 0o600); err != nil {
			return "", err
		}
		fmt.Fprintf(&tlsCerts, "  certificates:\n    - certFile: %s\n      keyFile: %s\n", certPath(dir, r.ID), keyPath(dir, r.ID))
	}

	// ── assemble the document ──
	var b strings.Builder
	fmt.Fprintf(&b, "# Auto-generated by Rigger (Proxy Service) — route %d (%s). Do not edit.\n", r.ID, r.Name)
	b.WriteString("http:\n")
	b.WriteString("  routers:\n")
	b.WriteString(routers.String())
	if services.Len() > 0 {
		b.WriteString("  services:\n")
		b.WriteString(services.String())
	}
	if middlewares.Len() > 0 {
		b.WriteString("  middlewares:\n")
		b.WriteString(middlewares.String())
	}
	if transports.Len() > 0 {
		b.WriteString("  serversTransports:\n")
		b.WriteString(transports.String())
	}
	if tlsCerts.Len() > 0 {
		b.WriteString("tls:\n")
		b.WriteString(tlsCerts.String())
	}
	return b.String(), nil
}

// writeRouter emits a single router block (rule, entrypoint, service, middlewares, tls).
func writeRouter(b *strings.Builder, name, rule, entry, service string, mws []string, tlsOn bool, r Route, priority int) {
	fmt.Fprintf(b, "    %s:\n", name)
	fmt.Fprintf(b, "      rule: %q\n", rule)
	fmt.Fprintf(b, "      entryPoints: [%q]\n", entry)
	fmt.Fprintf(b, "      service: %s\n", service)
	if priority > 0 {
		fmt.Fprintf(b, "      priority: %d\n", priority)
	}
	if len(mws) > 0 {
		quoted := make([]string, len(mws))
		for i, m := range mws {
			quoted[i] = strconv.Quote(m)
		}
		fmt.Fprintf(b, "      middlewares: [%s]\n", strings.Join(quoted, ", "))
	}
	if tlsOn {
		switch {
		case r.ACMEEmail != "":
			// Per-route ACME email override → cert issued out-of-band under that email
			// (see issueOverrideCerts); Traefik serves the SNI-matching file cert.
			b.WriteString("      tls: {}\n")
		case r.TLSMode == "le-http":
			b.WriteString("      tls:\n        certResolver: letsencrypt\n")
		case r.TLSMode == "le-dns":
			b.WriteString("      tls:\n        certResolver: dns\n")
		default: // existing | custom — Traefik serves the SNI-matching stored cert
			b.WriteString("      tls: {}\n")
		}
	}
}

// routeRule returns the Traefik matcher and a router priority (0 = default/none).
// The catch-all default route gets a low priority (2) so real routers always win.
func routeRule(r Route) (string, int) {
	if r.IsDefault {
		if r.DefaultMode == "page" {
			return "", 0 // built-in rigger-fallback already serves the page
		}
		return "PathPrefix(`/`)", 2
	}
	return combineRule(hostsExpr(r.Host), r.PathPrefix), 0
}

// splitHosts parses the multi-domain host field (comma/space/newline separated).
func splitHosts(field string) []string {
	repl := strings.NewReplacer(",", " ", "\n", " ", "\t", " ")
	return strings.Fields(repl.Replace(field))
}

// hostsExpr builds "Host(`a`) || Host(`b`)" from the multi-domain host field.
func hostsExpr(field string) string {
	var parts []string
	for _, h := range splitHosts(field) {
		parts = append(parts, "Host(`"+h+"`)")
	}
	return strings.Join(parts, " || ")
}

// combineRule joins a host group and an optional path prefix, parenthesizing a
// multi-host (`||`) group before the `&&`.
func combineRule(hostGroup, pathPrefix string) string {
	pathPrefix = strings.TrimSpace(pathPrefix)
	if hostGroup == "" {
		if pathPrefix != "" {
			return "PathPrefix(`" + pathPrefix + "`)"
		}
		return ""
	}
	if pathPrefix == "" {
		return hostGroup
	}
	if strings.Contains(hostGroup, "||") {
		hostGroup = "(" + hostGroup + ")"
	}
	return hostGroup + " && PathPrefix(`" + pathPrefix + "`)"
}

// headersMiddleware builds the optional headers middleware (HSTS + baseline security
// headers). Returns "" when neither is requested.
func headersMiddleware(id string, r Route) string {
	if r.HSTSSeconds <= 0 && !r.SecurityHeaders {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "    %s-headers:\n      headers:\n", id)
	if r.HSTSSeconds > 0 {
		fmt.Fprintf(&b, "        stsSeconds: %d\n", r.HSTSSeconds)
		fmt.Fprintf(&b, "        stsIncludeSubdomains: %t\n", r.HSTSSubdomains)
		fmt.Fprintf(&b, "        stsPreload: %t\n", r.HSTSPreload)
	}
	if r.SecurityHeaders {
		b.WriteString("        frameDeny: true\n")
		b.WriteString("        contentTypeNosniff: true\n")
		b.WriteString("        browserXssFilter: true\n")
		b.WriteString("        referrerPolicy: \"strict-origin-when-cross-origin\"\n")
	}
	return b.String()
}

func upstreamURL(u Upstream) string {
	scheme := u.Scheme
	if scheme == "" {
		scheme = "http"
	}
	host := u.Host
	if u.Port > 0 {
		host = host + ":" + strconv.Itoa(u.Port)
	}
	return scheme + "://" + host
}

func splitCSV(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}
