package proxyroutes

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mansoor/rigger/ui/internal/db"
)

// Shared access-list middlewares: workspace-scoped Access Lists are rendered ONCE into the file
// provider as named middlewares (`acl-<ws>-<id>-auth/-ipallow/-geo`), so the Docker-provider
// routers composegen emits for hosted apps can reference them by `name@file` — one definition
// reused across many app routers. Global (Proxy Service) lists are NOT rendered here; they're
// inlined per-route by routeYAML. See docs/design/workspace-plugins-and-access-lists.md.

// aclPrefix is an access list's Traefik middleware / file basename ("acl-<ws|global>-<id>").
func aclPrefix(a AccessList) string {
	ws := a.Workspace
	if ws == "" {
		ws = "global"
	}
	return "acl-" + ws + "-" + strconv.FormatInt(a.ID, 10)
}

// allowCIDRs returns the addresses of the "allow" rules (Traefik ipAllowList is allow-only).
func allowCIDRs(rules []AccessRule) []string {
	var out []string
	for _, r := range rules {
		if r.Action == "allow" {
			if a := strings.TrimSpace(r.Address); a != "" {
				out = append(out, a)
			}
		}
	}
	return out
}

// SharedACLMiddlewareNames returns the `name@file` middleware references composegen should attach
// to an app router to apply this access list (auth, then ip-allow, then geo — chain order). geo is
// included only when the GeoIP plugin is enabled instance-wide. Empty when the list has no
// enforceable rules.
func SharedACLMiddlewareNames(a AccessList, geoEnabled bool) []string {
	var sink strings.Builder // throwaway — we only want the names, computed identically to the writer
	names := writeAccessMiddlewares(&sink, aclPrefix(a), a.Users, a.PassAuth, allowCIDRs(a.Rules), a.GeoMode, a.Countries, geoEnabled)
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = n + "@file"
	}
	return out
}

// RenderSharedACLs (re)writes one `/dynamic/acl-<ws>-<id>.yml` per workspace-scoped access list
// that has at least one enforceable middleware, and prunes stale `acl-*.yml`. Idempotent;
// errors are returned (caller logs, never fatal). geoEnabled gates geoblock emission.
func RenderSharedACLs(d *db.DB, dir string, geoEnabled bool) error {
	st := NewStore(d)
	lists, err := st.ListAccessLists()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("proxyroutes: ensure %s: %w", dir, err)
	}
	want := map[string]bool{}
	for _, a := range lists {
		if a.Workspace == "" {
			continue // global lists are inlined by Proxy Service routes, not shared
		}
		var mw strings.Builder
		names := writeAccessMiddlewares(&mw, aclPrefix(a), a.Users, a.PassAuth, allowCIDRs(a.Rules), a.GeoMode, a.Countries, geoEnabled)
		if len(names) == 0 {
			continue // nothing enforceable → no fragment (and any old one gets pruned below)
		}
		var doc strings.Builder
		fmt.Fprintf(&doc, "# Auto-generated by Rigger (access list %q, workspace %q). Do not edit.\n", a.Name, a.Workspace)
		doc.WriteString("http:\n  middlewares:\n")
		doc.WriteString(mw.String())
		fname := aclPrefix(a) + ".yml"
		if err := os.WriteFile(filepath.Join(dir, fname), []byte(doc.String()), 0o644); err != nil {
			return fmt.Errorf("proxyroutes: write access list %d: %w", a.ID, err)
		}
		want[fname] = true
	}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		n := e.Name()
		if strings.HasPrefix(n, "acl-") && strings.HasSuffix(n, ".yml") && !want[n] {
			_ = os.Remove(filepath.Join(dir, n))
		}
	}
	return nil
}
