package main

import (
	"embed"
	"fmt"
	"io/fs"
	"log"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mansoor/rigger/ui/api"
	"github.com/mansoor/rigger/ui/internal/acme"
	"github.com/mansoor/rigger/ui/internal/alerts"
	"github.com/mansoor/rigger/ui/internal/auth"
	"github.com/mansoor/rigger/ui/internal/config"
	"github.com/mansoor/rigger/ui/internal/crypto"
	"github.com/mansoor/rigger/ui/internal/db"
	"github.com/mansoor/rigger/ui/internal/imagecheck"
	"github.com/mansoor/rigger/ui/internal/maintenance"
	"github.com/mansoor/rigger/ui/internal/metrics"
	"github.com/mansoor/rigger/ui/internal/notify"
	"github.com/mansoor/rigger/ui/internal/pipelines"
	"github.com/mansoor/rigger/ui/internal/remotehost"
	"github.com/mansoor/rigger/ui/internal/settings"
	"github.com/mansoor/rigger/ui/internal/shell"
)

//go:embed all:dist
var frontendFS embed.FS

// outboundIP returns the local IP of the interface used to reach the internet.
// The UDP "connect" performs a route lookup and binds a local address but sends
// nothing — so this works offline and never generates traffic. When run in the
// host network namespace (via `--network host`) this is the host's real LAN/
// public IP; in the control-plane container's own namespace it would be the
// bridge IP, which is why detection runs host-networked.
func outboundIP() string {
	conn, err := net.Dial("udp", "1.1.1.1:80")
	if err != nil {
		return ""
	}
	defer conn.Close()
	if a, ok := conn.LocalAddr().(*net.UDPAddr); ok {
		return a.IP.String()
	}
	return ""
}

// seedLoadingMiddleware writes the Traefik file-provider definition for the shared
// "rigger-loading" errors middleware (referenced by app routers as
// rigger-loading@file). Best-effort: any failure is logged and ignored.
func seedLoadingMiddleware() {
	dir := acme.DefaultDynamicDir
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Printf("loading-middleware: cannot ensure %s: %v (skipping)", dir, err)
		return
	}
	const cfg = `# Auto-generated by Rigger on boot — do not edit.
# Shared errors middleware: when an app's backend is down (502/503/504 while it's
# still starting or crash-looping), serve the friendly retry page instead of a
# bare gateway error. App routers reference this as rigger-loading@file.
http:
  middlewares:
    rigger-loading:
      errors:
        status:
          - "502-504"
        service: rigger-fallback@docker
        query: "/"
`
	if err := os.WriteFile(dir+"/rigger-loading.yml", []byte(cfg), 0o644); err != nil {
		log.Printf("loading-middleware: write failed: %v (skipping)", err)
	}
}

// seedMaintenanceService writes the shared Traefik file-provider service that per-env
// maintenance routers point at (rigger-maint@file → the always-on rigger UI, which
// renders the "under maintenance" page). Best-effort, like seedLoadingMiddleware.
func seedMaintenanceService() {
	dir := maintenance.DynDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Printf("maintenance-service: cannot ensure %s: %v (skipping)", dir, err)
		return
	}
	if err := os.WriteFile(dir+"/rigger-maint.yml", []byte(maintenance.SeedServiceYAML), 0o644); err != nil {
		log.Printf("maintenance-service: write failed: %v (skipping)", err)
	}
}

// seedDNSToken materializes the Cloudflare DNS-01 token into the shared volume file
// Traefik (CF_DNS_API_TOKEN_FILE) and out-of-band lego both read. Source of truth is
// the admin-managed app_settings value; a legacy src/.env CF_DNS_API_TOKEN is migrated
// into settings once so existing installs keep working. Idempotent + best-effort.
func seedDNSToken(d *db.DB) {
	tok := strings.TrimSpace(settings.AppSetting(d, "apps_dns_token"))
	if tok == "" {
		if env := strings.TrimSpace(os.Getenv("CF_DNS_API_TOKEN")); env != "" {
			if err := settings.SetAppSetting(d, "apps_dns_token", env); err != nil {
				log.Printf("dns-token: migrate from env failed: %v", err)
			}
			tok = env
		}
	}
	if tok == "" {
		return
	}
	if err := acme.New(nil).SetToken(tok); err != nil {
		log.Printf("dns-token: write to shared volume failed: %v (DNS-01 may be unavailable)", err)
	}
}

func main() {
	// Subcommands run a one-shot task and exit instead of starting the server.
	if len(os.Args) > 1 && os.Args[1] == "init-workspace" {
		os.Exit(runInitWorkspace(os.Args[2:]))
	}
	// detect-host-ip prints the host's primary outbound IP and exits. The control
	// plane runs this in a throwaway `--network host` container so the lookup
	// happens in the HOST network namespace (the server's own namespace only sees
	// the 172.x bridge). A UDP "connect" selects the outbound route without sending
	// any packet — its local address is the IP the host reaches the internet on.
	if len(os.Args) > 1 && os.Args[1] == "detect-host-ip" {
		if ip := outboundIP(); ip != "" {
			fmt.Println(ip)
			os.Exit(0)
		}
		os.Exit(1)
	}

	cfg := config.Load()

	// ── Database ──────────────────────────────────────────────────────────────
	database, err := db.Open(cfg.DataDir)
	if err != nil {
		log.Fatalf("db: %v", err)
	}

	// Seed the app_host setting from the installer-detected host IP on first boot.
	// The containerized server can't detect the host's LAN/public IP itself (it
	// only sees its bridge IP), so the installer captures it and passes it via
	// RIGGER_APP_HOST. Only seed when unset — never clobber an admin's edit.
	if hostIP := strings.TrimSpace(os.Getenv("RIGGER_APP_HOST")); hostIP != "" && settings.AppSetting(database, "app_host") == "" {
		if err := settings.SetAppSetting(database, "app_host", hostIP); err == nil {
			log.Printf("settings: seeded app_host=%s from RIGGER_APP_HOST", hostIP)
		}
	}

	// Any pipeline run left "running" was stranded by a previous shutdown (its
	// goroutine died before finalizing). Sweep them to cancelled so the UI never
	// shows a stranded in-flight run.
	if n, rerr := pipelines.ReconcileRunning(database, time.Now().UnixMilli()); rerr == nil && n > 0 {
		log.Printf("pipelines: reconciled %d orphaned running run(s) → cancelled", n)
	}

	// ── Services ──────────────────────────────────────────────────────────────
	authSvc := auth.NewService(database, cfg.JWTSecret, cfg.JWTExpiry)
	// Phase 7: SSH connection pool + the AES key (derived from JWT secret) that
	// decrypts host keys, so the bridge can run commands on remote workspaces.
	hostPool := remotehost.NewPool()
	cryptoKey, _ := crypto.DeriveKey([]byte(cfg.JWTSecret))
	bridge := shell.NewBridge(cfg.WorkspacesDir, cfg.RemoteWorkspacesDir, cfg.ToolkitRoot, database, hostPool, cryptoKey)

	// Phase 6.5 finish: commands run natively in Go, so workspaces no longer
	// need a generated run.sh. Sweep away any leftover from older versions.
	removeRunSh(cfg.WorkspacesDir)

	// Image update cache — populated by hourly background checker
	imgCache := imagecheck.NewCache()
	imagecheck.RunBackground(imgCache, cfg.WorkspacesDir)

	// Notifications (Phase 6b): email is delivered directly over SMTP; everything
	// else via Apprise. The Apprise backend is in-process apprise-go by default
	// (no sidecar); setting APPRISE_URL switches to the Apprise API sidecar.
	var appriseBackend notify.AppriseBackend
	if cfg.AppriseURL != "" {
		appriseBackend = notify.NewAppriseClient(cfg.AppriseURL)
		log.Printf("Notifications: Apprise sidecar at %s", cfg.AppriseURL)
	} else {
		appriseBackend = notify.NewEmbeddedApprise()
		log.Printf("Notifications: embedded apprise-go")
	}
	notifier := notify.NewDispatcher(database, appriseBackend)

	// Alerting (Phase 6): SSE broker for pushing alert events + the background
	// rule evaluator that turns rule conditions into alert events every 60s and
	// dispatches notifications to each rule's assigned channels.
	alertBroker := alerts.NewBroker()
	alerts.NewEvaluator(database, cfg.WorkspacesDir, imgCache, alertBroker, notifier).Run()

	// Metrics history (Phase 6d): background collector samples per-env CPU/memory/
	// disk every METRICS_INTERVAL_SECONDS (default 30s). A separate tiered job
	// thins old rows (full-res ≤24h, 1-min 24–120h, 5-min beyond) and prunes to
	// 90 days. The same interval is reported to the UI via /api/metrics/config.
	metricsInterval := time.Duration(metrics.IntervalSeconds()) * time.Second
	metrics.NewCollector(database, cfg.WorkspacesDir, metricsInterval, bridge).Run()

	// Materialize the Cloudflare DNS token (admin-set in Settings → General, or a
	// legacy src/.env CF_DNS_API_TOKEN) into the shared volume file Traefik + lego
	// read, so DNS-01 wildcard/override certs work without a manual .env edit. Runs
	// before the renewer/issuer construct their own acme.New so they see the token.
	// Idempotent + best-effort.
	seedDNSToken(database)

	// Renew out-of-band override certs (per-env/workspace ACME email, Phase 2): every
	// 12h, re-issue any tracked cert within 30 days of expiry via lego (DNS-01). Idle
	// when no Cloudflare token is set. Traefik auto-renews its own resolver certs.
	acmeRenewer := acme.NewRenewer(database, acme.New(nil))
	// Per-workspace wildcard certs are issued under a workspace's OWN Cloudflare token
	// (its own zone); resolve it (decrypted) so the renewer renews them too.
	acmeRenewer.TokenFor = func(ws string) string { return settings.WorkspaceDNSToken(database, cryptoKey, ws) }
	acmeRenewer.Run()

	// Seed the shared "loading" errors middleware into the Traefik file-provider dir
	// (/dynamic, hot-reloaded). App routers reference rigger-loading@file so a backend
	// that's still starting / crash-looping serves the friendly retry page on
	// 502/503/504 instead of a bare gateway error. Defined here (rewritten on every
	// boot, so a one-click update that recreates only the rigger container still
	// registers it) rather than via fallback-container labels, which the updater
	// doesn't recreate. Best-effort: a write failure (e.g. dev box w/o the volume)
	// just means no loading page — never fatal.
	seedLoadingMiddleware()
	seedMaintenanceService() // shared rigger-maint@file service for per-env maintenance routers

	handler := api.NewHandler(authSvc, database, bridge, cfg.WorkspacesDir, cfg.RemoteWorkspacesDir, cfg.TemplatesDir, cfg.DataDir, imgCache, alertBroker, notifier, cfg.JWTSecret)

	// Start daily automated housekeeping (networks + dangling images) at 03:00 UTC
	handler.StartHousekeepingScheduler(3)
	handler.MigrateBackupConfig()   // one-time: legacy config.backup → per-env schedules
	handler.MigrateLegacyDomains()  // one-time: legacy per-env domain → verified primary custom domain
	handler.RenderProxyRoutes()     // re-render the Proxy Service file-provider config (drift repair)
	handler.StartBackupScheduler()      // Phase 11 — per-env interval-based backup schedules
	handler.StartPreviewReaper()        // tear down preview envs past their TTL (missed-close safety net)
	handler.StartMaintenanceScheduler() // reconcile per-env maintenance windows → Traefik fragments

	// ── Router ────────────────────────────────────────────────────────────────
	mux := http.NewServeMux()

	// Setup / auth (no JWT required)
	mux.HandleFunc("GET /api/setup/status", handler.SetupStatus)
	mux.HandleFunc("POST /api/setup", handler.Setup)
	mux.HandleFunc("POST /api/auth/login", handler.Login)
	mux.HandleFunc("POST /api/auth/logout", handler.Logout)
	mux.HandleFunc("POST /api/auth/refresh", handler.Refresh)
	mux.Handle("POST /api/auth/password", authSvc.Middleware(http.HandlerFunc(handler.ChangePassword)))

	// Invite registration + email verification (Phase 5.1b) — token-authenticated, no JWT.
	mux.HandleFunc("GET /api/register/info", handler.RegisterInfo)
	mux.HandleFunc("POST /api/register/complete", handler.CompleteRegistration)
	mux.HandleFunc("POST /api/auth/verify-email", handler.VerifyEmail)
	// Public self-service: password policy (for form hints) + forgot/reset-password
	// (token-authenticated, no JWT). reset is rate-limited + non-enumerating.
	mux.HandleFunc("GET /api/auth/password-policy", handler.PasswordPolicyInfo)
	mux.HandleFunc("POST /api/auth/forgot-password", handler.ForgotPassword)
	mux.HandleFunc("POST /api/auth/reset-password", handler.ResetPassword)
	// Self-service (JWT) — resend own verification, update own profile.
	mux.Handle("POST /api/auth/resend-verification", authSvc.Middleware(http.HandlerFunc(handler.ResendVerification)))
	mux.Handle("GET /api/auth/profile", authSvc.Middleware(http.HandlerFunc(handler.GetProfile)))
	mux.Handle("PUT /api/auth/profile", authSvc.Middleware(http.HandlerFunc(handler.UpdateProfile)))
	// Per-user appearance (W7) — resolves user ?? workspace ?? global default.
	mux.Handle("GET /api/auth/appearance", authSvc.Middleware(http.HandlerFunc(handler.GetAppearance)))
	mux.Handle("PUT /api/auth/appearance", authSvc.Middleware(http.HandlerFunc(handler.PutAppearance)))
	// Per-user destructive-confirm override (resolves user ?? workspace ?? global, with per-tier lock).
	mux.Handle("GET /api/auth/confirm", authSvc.Middleware(http.HandlerFunc(handler.GetConfirm)))
	mux.Handle("PUT /api/auth/confirm", authSvc.Middleware(http.HandlerFunc(handler.PutConfirm)))
	// Optional 2FA (TOTP) self-service.
	mux.Handle("GET /api/auth/2fa", authSvc.Middleware(http.HandlerFunc(handler.TwoFAStatus)))
	mux.Handle("POST /api/auth/2fa/begin", authSvc.Middleware(http.HandlerFunc(handler.TwoFABegin)))
	mux.Handle("POST /api/auth/2fa/enable", authSvc.Middleware(http.HandlerFunc(handler.TwoFAEnable)))
	mux.Handle("POST /api/auth/2fa/disable", authSvc.Middleware(http.HandlerFunc(handler.TwoFADisable)))
	mux.Handle("POST /api/auth/2fa/recovery-codes", authSvc.Middleware(http.HandlerFunc(handler.TwoFARegenerateCodes)))

	// Rigger's own build version (self-update Phase 0).
	mux.Handle("GET /api/version", authSvc.Middleware(http.HandlerFunc(handler.GetVersion)))

	// Access requests (roadmap 9): any signed-in user can request access; workspace
	// admins / super-admins review. All behind auth middleware (claims present);
	// per-action authorization is enforced inside the handlers.
	mux.Handle("GET /api/access-requests/targets", authSvc.Middleware(http.HandlerFunc(handler.AccessRequestTargets)))
	mux.Handle("GET /api/access-requests/mine", authSvc.Middleware(http.HandlerFunc(handler.ListMyAccessRequests)))
	mux.Handle("GET /api/access-requests", authSvc.Middleware(http.HandlerFunc(handler.ListPendingAccessRequests)))
	mux.Handle("POST /api/access-requests", authSvc.Middleware(http.HandlerFunc(handler.CreateAccessRequest)))
	mux.Handle("POST /api/access-requests/{id}/approve", authSvc.Middleware(http.HandlerFunc(handler.DecideAccessRequest)))
	mux.Handle("POST /api/access-requests/{id}/reject", authSvc.Middleware(http.HandlerFunc(handler.DecideAccessRequest)))

	// adminOnly gates a handler to global super-admin callers (Phase 5 RBAC).
	// Wrapped inside authSvc.Middleware so claims are present.
	adminOnly := authSvc.RequireSuperadmin()

	// Self-update Phase 2 — check for a newer Rigger release (admin only).
	mux.Handle("GET /api/updates/check", authSvc.Middleware(adminOnly(http.HandlerFunc(handler.CheckUpdates))))
	// Self-update Phase 3 — apply / rollback via a detached recreate helper (admin only).
	mux.Handle("POST /api/updates/apply", authSvc.Middleware(adminOnly(http.HandlerFunc(handler.ApplyUpdate))))
	mux.Handle("POST /api/updates/rollback", authSvc.Middleware(adminOnly(http.HandlerFunc(handler.RollbackUpdate))))

	// User management (Phase 5 / roadmap 10a) — admin only.
	mux.Handle("/api/users", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case "GET":
			handler.ListUsers(w, r)
		case "POST":
			handler.CreateUser(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))
	mux.Handle("/api/users/", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == "POST" && hasSuffix(r.URL.Path, "/resend-invite"):
			handler.ResendInvite(w, r)
		case r.Method == "PUT":
			handler.UpdateUser(w, r)
		case r.Method == "DELETE":
			handler.DeleteUser(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))

	// Protected API routes (JWT middleware applied per-route group)
	protected := authSvc.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Phase 5.2b: enforce workspace-scoped access before dispatching ws sub-routes.
		if matchPrefix(r.URL.Path, "/api/workspaces/") && !handler.GateWorkspace(w, r) {
			return
		}
		switch {
		case r.Method == "GET" && r.URL.Path == "/api/templates":
			handler.ListTemplates(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/tools/save-template":
			handler.SaveTemplate(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/tools/workspace-backup":
			handler.StartWorkspaceBackup(w, r)
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/tools/backup-jobs/"):
			r.SetPathValue("id", pathSegment(r.URL.Path, 3))
			handler.GetBackupJob(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/tools/workspace-archives":
			handler.ListWorkspaceArchives(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/tools/workspace-archives/upload":
			handler.UploadWorkspaceArchive(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/tools/workspace-archives/") && hasSuffix(r.URL.Path, "/restore"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.RestoreWorkspaceFromArchive(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/tools/workspace-archives/") && hasSuffix(r.URL.Path, "/sync"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.SyncWorkspaceArchive(w, r)
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/tools/workspace-archives/"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.DownloadWorkspaceArchive(w, r)
		case r.Method == "DELETE" && matchPrefix(r.URL.Path, "/api/tools/workspace-archives/"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.DeleteWorkspaceArchive(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/tools/workspace-restore":
			handler.RestoreWorkspace(w, r)
		// Configuration snapshots (.rws) — config-only, separate from full backups.
		case r.Method == "POST" && r.URL.Path == "/api/tools/workspace-snapshots":
			handler.CreateWorkspaceSnapshot(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/tools/workspace-snapshots/upload":
			handler.UploadWorkspaceSnapshot(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/tools/workspace-snapshots":
			handler.ListWorkspaceSnapshots(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/tools/workspace-snapshots/") && hasSuffix(r.URL.Path, "/rollback"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.RollbackWorkspaceSnapshot(w, r)
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/tools/workspace-snapshots/"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.DownloadWorkspaceSnapshot(w, r)
		case r.Method == "DELETE" && matchPrefix(r.URL.Path, "/api/tools/workspace-snapshots/"):
			r.SetPathValue("filename", pathSegment(r.URL.Path, 3))
			handler.DeleteWorkspaceSnapshot(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/templates/") && hasSuffix(r.URL.Path, "/use"):
			r.SetPathValue("name", pathSegment(r.URL.Path, 2))
			handler.RecordTemplateUse(w, r)
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/templates/") && hasSuffix(r.URL.Path, "/raw"):
			r.SetPathValue("name", pathSegment(r.URL.Path, 2))
			handler.GetTemplateRaw(w, r)
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/templates/"):
			r.SetPathValue("name", pathSegment(r.URL.Path, 2))
			handler.GetTemplate(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/debug/paths":
			handler.DebugPaths(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/metrics/config":
			handler.GetMetricsConfig(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/stats":
			handler.GetStats(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/live-stats":
			handler.GetLiveStats(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/activity":
			handler.GetAllActivity(w, r)
		case r.Method == "POST" && r.URL.Path == "/api/port-check":
			handler.PortCheck(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/keys/suggest":
			handler.SuggestKey(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/keys/check":
			handler.CheckKey(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/backups/coverage":
			handler.GetBackupCoverage(w, r)
		case r.Method == "GET" && r.URL.Path == "/api/backups":
			handler.ListBackups(w, r)
		case r.Method == "DELETE" && matchPrefix(r.URL.Path, "/api/backups/"):
			// /api/backups/{workspace}/{project}/{env}/{date}
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 3))
			r.SetPathValue("env", pathSegment(r.URL.Path, 4))
			r.SetPathValue("date", pathSegment(r.URL.Path, 5))
			handler.DeleteBackup(w, r)
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "hosts":
			// Workspace-scoped Remote Hosts (Phase 3). Matched ahead of the generic
			// /api/workspaces/{ws}/projects/... routing below.
			// /api/workspaces/{ws}/hosts[/{id}[/test|/stats]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("hostid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			sub := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceHosts(w, r)
			case r.Method == "GET" && sub == "stats":
				handler.WorkspaceHostStats(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceHost(w, r)
			case r.Method == "POST" && sub == "test":
				handler.TestWorkspaceHost(w, r)
			case r.Method == "POST" && sub == "build-only":
				handler.SetWorkspaceHostBuildOnly(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceHost(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceHost(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "registries":
			// Workspace-scoped Docker Registries (Phase 3).
			// /api/workspaces/{ws}/registries[/{id}[/test]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("regid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			sub := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceRegistries(w, r)
			case r.Method == "POST" && id == "test-credentials":
				handler.TestRegistryCredentials(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceRegistry(w, r)
			case r.Method == "POST" && sub == "test":
				handler.TestWorkspaceRegistry(w, r)
			case r.Method == "POST" && sub == "system":
				handler.MarkWorkspaceRegistrySystem(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceRegistry(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceRegistry(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "git-providers":
			// Workspace-scoped Git provider connections (Phase 12 — private repos).
			// /api/workspaces/{ws}/git-providers[/{id}[/test]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("gpid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			sub := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceGitProviders(w, r)
			case r.Method == "POST" && id == "github" && sub == "manifest":
				handler.StartGitHubAppManifest(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceGitProvider(w, r)
			case r.Method == "POST" && sub == "test":
				handler.TestWorkspaceGitProvider(w, r)
			case r.Method == "POST" && sub == "github":
				handler.GitHubAppInstallURL(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceGitProvider(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceGitProvider(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "api-key-scopes":
			// Scope catalog for the workspace API-key create form (static metadata).
			handler.GetApiKeyScopes(w, r)
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "api-keys":
			// Workspace-scoped API keys (workspace admin only — gated by wsMinRole).
			// /api/workspaces/{ws}/api-keys[/{id}]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("keyid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceApiKeys(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceApiKey(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceApiKey(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceApiKey(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "backup-targets":
			// Workspace-scoped Backup Targets (Phase 3).
			// /api/workspaces/{ws}/backup-targets[/{id}[/test]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("targetid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			sub := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceBackupTargets(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceBackupTarget(w, r)
			case r.Method == "POST" && sub == "test":
				handler.TestWorkspaceBackupTarget(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceBackupTarget(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceBackupTarget(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "notification-channels":
			// Workspace-scoped Notification Channels (Phase 3).
			// /api/workspaces/{ws}/notification-channels[/{id}[/test]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("channelid", pathSegment(r.URL.Path, 4))
			id := pathSegment(r.URL.Path, 4)
			sub := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceNotificationChannels(w, r)
			case r.Method == "POST" && id == "":
				handler.CreateWorkspaceNotificationChannel(w, r)
			case r.Method == "POST" && sub == "test":
				handler.TestWorkspaceNotificationChannel(w, r)
			case r.Method == "PUT" && id != "":
				handler.UpdateWorkspaceNotificationChannel(w, r)
			case r.Method == "DELETE" && id != "":
				handler.DeleteWorkspaceNotificationChannel(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "members":
			// Workspace membership (Phase 5.2). /api/workspaces/{ws}/members[/{id}[/projects/{proj}]]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("memberid", pathSegment(r.URL.Path, 4))
			r.SetPathValue("projkey", pathSegment(r.URL.Path, 6))
			id := pathSegment(r.URL.Path, 4)
			isProj := pathSegment(r.URL.Path, 5) == "projects"
			switch {
			case r.Method == "GET" && id == "candidates":
				handler.ListMemberCandidates(w, r)
			case r.Method == "GET" && id == "":
				handler.ListWorkspaceMembers(w, r)
			case r.Method == "PUT" && id != "" && isProj:
				handler.SetProjectOverride(w, r)
			case r.Method == "DELETE" && id != "" && isProj:
				handler.RemoveProjectOverride(w, r)
			case r.Method == "PUT" && id != "":
				handler.SetWorkspaceMember(w, r)
			case r.Method == "DELETE" && id != "":
				handler.RemoveWorkspaceMember(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "alerts":
			// Workspace-scoped Alert Rules (Phase 3).
			// /api/workspaces/{ws}/alerts/rules[/{id}]
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("ruleid", pathSegment(r.URL.Path, 5))
			id := pathSegment(r.URL.Path, 5)
			switch {
			case r.Method == "GET" && pathSegment(r.URL.Path, 4) == "rules" && id == "":
				handler.ListWorkspaceAlertRules(w, r)
			case r.Method == "POST" && pathSegment(r.URL.Path, 4) == "rules" && id == "":
				handler.CreateWorkspaceAlertRule(w, r)
			case r.Method == "PUT" && pathSegment(r.URL.Path, 4) == "rules" && id != "":
				handler.UpdateWorkspaceAlertRule(w, r)
			case r.Method == "DELETE" && pathSegment(r.URL.Path, 4) == "rules" && id != "":
				handler.DeleteWorkspaceAlertRule(w, r)
			default:
				http.NotFound(w, r)
			}
		case matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "settings":
			// Per-workspace general settings (Phase 3). /api/workspaces/{ws}/settings
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			switch r.Method {
			case "GET":
				handler.GetWorkspaceSettings(w, r)
			case "PUT":
				handler.PutWorkspaceSettings(w, r)
			default:
				http.NotFound(w, r)
			}
		case r.Method == "GET" && r.URL.Path == "/api/workspaces":
			handler.ListWorkspaces(w, r) // list parent-tier workspaces
		case r.Method == "POST" && r.URL.Path == "/api/workspaces":
			handler.CreateWorkspaceTier(w, r) // create a parent-tier workspace
		case r.Method == "GET" && matchPrefix(r.URL.Path, "/api/workspaces/") && !hasSuffix(r.URL.Path, "/action"):
			// /api/workspaces/{ws}/projects/{name}/{sub}/{env}/{subsub}/{service}/{caction}
			ws := pathSegment(r.URL.Path, 2)
			name := pathSegment(r.URL.Path, 4)   // project
			sub := pathSegment(r.URL.Path, 5)    // activity | action-runs | config | envs
			env := pathSegment(r.URL.Path, 6)    // env name (when sub=envs)
			subsub := pathSegment(r.URL.Path, 7) // vars | status | compose | containers ...
			r.SetPathValue("workspace", ws)
			r.SetPathValue("name", name)
			r.SetPathValue("env", env)
			switch {
			case name == "":
				handler.ListProjects(w, r) // GET /api/workspaces/{ws}/projects
			case sub == "activity":
				handler.GetActivity(w, r)
			case sub == "action-runs":
				handler.GetActionRuns(w, r)
			case sub == "config":
				handler.GetConfig(w, r)
			case sub == "template-draft":
				handler.GenerateTemplateDraft(w, r)
			case sub == "envs" && subsub == "status":
				handler.GetEnvStatus(w, r)
			case sub == "envs" && subsub == "vars":
				handler.GetEnvVars(w, r)
			case sub == "envs" && subsub == "secret-events":
				handler.GetSecretEvents(w, r)
			case sub == "envs" && subsub == "compose":
				handler.GetCompose(w, r)
			case sub == "envs" && subsub == "image-updates":
				handler.GetImageUpdates(w, r)
			case sub == "envs" && subsub == "containers":
				// .../containers → list; .../containers/{service}/{action} → per-container
				if svc := pathSegment(r.URL.Path, 8); svc != "" {
					r.SetPathValue("service", svc)
					switch pathSegment(r.URL.Path, 9) {
					case "inspect":
						handler.ContainerInspect(w, r)
					case "stats":
						handler.ContainerStats(w, r)
					case "top":
						handler.ContainerTop(w, r)
					case "image-history":
						handler.ContainerImageHistory(w, r)
					case "files":
						handler.FileList(w, r)
					case "file":
						handler.FileView(w, r)
					case "file-download":
						handler.FileDownload(w, r)
					default:
						http.NotFound(w, r)
					}
				} else {
					handler.GetContainers(w, r)
				}
			case sub == "envs" && subsub == "metrics":
				handler.GetEnvMetrics(w, r)
			case sub == "envs" && subsub == "backup-stats":
				handler.GetBackupStats(w, r)
			case sub == "envs" && subsub == "backup-services":
				handler.GetBackupServices(w, r)
			default:
				handler.GetWorkspace(w, r)
			}
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/action"):
			// /api/workspaces/{ws}/projects/{name}/envs/{env}/action
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			handler.ActionHTTP(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 7) == "containers":
			// /api/workspaces/{ws}/projects/{name}/envs/{env}/containers/{service}/{action}
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			r.SetPathValue("service", pathSegment(r.URL.Path, 8))
			switch pathSegment(r.URL.Path, 9) {
			case "files-upload":
				handler.FileUpload(w, r)
			case "file-rename":
				handler.FileRename(w, r)
			case "file-chmod":
				handler.FileChmod(w, r)
			case "file-mkdir":
				handler.FileMkdir(w, r)
			case "file-new":
				handler.FileNew(w, r)
			default:
				http.NotFound(w, r)
			}
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/transfer"):
			// POST /api/workspaces/{key}/transfer — move projects to another workspace
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			handler.TransferWorkspace(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/migrate"):
			// /api/workspaces/{ws}/projects/{name}/migrate — move a project to another host
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			handler.MigrateWorkspace(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/rotate"):
			// /api/workspaces/{ws}/projects/{name}/envs/{env}/rotate
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			handler.RotateSecret(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/backup-sync"):
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			handler.SyncEnvBackup(w, r)
		case r.Method == "POST" && matchPrefix(r.URL.Path, "/api/workspaces/") && hasSuffix(r.URL.Path, "/restore-verify"):
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			handler.VerifyRestore(w, r)
		case r.Method == "PUT" && matchPrefix(r.URL.Path, "/api/workspaces/") && pathSegment(r.URL.Path, 3) == "":
			// PUT /api/workspaces/{key} — rename the workspace (no /projects/ segment)
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			handler.RenameWorkspaceTier(w, r)
		case r.Method == "PUT" && matchPrefix(r.URL.Path, "/api/workspaces/"):
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			sub := pathSegment(r.URL.Path, 5)
			env := pathSegment(r.URL.Path, 6)
			subsub := pathSegment(r.URL.Path, 7)
			r.SetPathValue("env", env)
			switch {
			case sub == "config":
				handler.PutConfig(w, r)
			case sub == "envs" && subsub == "compose":
				handler.PutCompose(w, r)
			case sub == "envs" && subsub == "host":
				handler.SetEnvHost(w, r)
			case sub == "envs" && subsub == "containers" && pathSegment(r.URL.Path, 9) == "file":
				r.SetPathValue("service", pathSegment(r.URL.Path, 8))
				handler.FileSave(w, r)
			default:
				http.NotFound(w, r)
			}
		case r.Method == "DELETE" && matchPrefix(r.URL.Path, "/api/workspaces/"):
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			switch {
			case pathSegment(r.URL.Path, 7) == "containers" && pathSegment(r.URL.Path, 9) == "file":
				// /api/workspaces/{ws}/projects/{name}/envs/{env}/containers/{service}/file
				r.SetPathValue("name", pathSegment(r.URL.Path, 4))
				r.SetPathValue("env", pathSegment(r.URL.Path, 6))
				r.SetPathValue("service", pathSegment(r.URL.Path, 8))
				handler.FileDelete(w, r)
			case pathSegment(r.URL.Path, 5) == "action-runs":
				r.SetPathValue("name", pathSegment(r.URL.Path, 4))
				handler.ClearActionRuns(w, r)
			case pathSegment(r.URL.Path, 4) != "":
				// DELETE /api/workspaces/{ws}/projects/{name} — delete a project
				r.SetPathValue("name", pathSegment(r.URL.Path, 4))
				handler.DeleteWorkspace(w, r)
			default:
				// DELETE /api/workspaces/{ws} — delete a whole workspace tier
				handler.DeleteWorkspaceTier(w, r)
			}
		case r.Method == "PATCH" && matchPrefix(r.URL.Path, "/api/workspaces/"):
			r.SetPathValue("workspace", pathSegment(r.URL.Path, 2))
			r.SetPathValue("name", pathSegment(r.URL.Path, 4))
			r.SetPathValue("env", pathSegment(r.URL.Path, 6))
			handler.UpdateEnvVars(w, r)
		default:
			http.NotFound(w, r)
		}
	}))

	mux.Handle("/api/debug/", protected)
	mux.Handle("/api/workspaces", protected)
	mux.Handle("/api/workspaces/", protected)

	// SSE: Docker container events (auth via ?token= query param)
	mux.HandleFunc("/api/events", handler.StreamEvents)

	// WebSocket: create workspace (streams bootstrap output)
	mux.HandleFunc("/api/workspaces/create", handler.CreateWorkspace)

	// Stats (dashboard)
	mux.Handle("/api/metrics/config", protected)
	mux.Handle("/api/stats", protected)
	mux.Handle("/api/live-stats", protected)

	// Global activity feed
	mux.Handle("/api/activity", protected)

	// Host-aware port-conflict check (New/Edit workspace)
	mux.Handle("/api/port-check", protected)

	// Key suggestion + availability check (workspace/project create)
	mux.Handle("/api/keys/", protected)

	// Backups (cross-workspace listing)
	mux.Handle("/api/backups", protected)
	mux.Handle("/api/backups/", protected)

	// Templates
	mux.Handle("/api/templates", protected)
	mux.Handle("/api/templates/", protected)
	mux.Handle("/api/tools/", protected)

	// Settings (backup targets + docker registries) — global, admin only
	mux.Handle("/api/settings/", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		switch {
		// General settings (ACME email, Rigger domain)
		case r.Method == "GET" && path == "/api/settings/general":
			handler.GetGeneralSettings(w, r)
		case r.Method == "PUT" && path == "/api/settings/general":
			handler.PutGeneralSettings(w, r)
		case r.Method == "GET" && path == "/api/settings/detect-host-ip":
			handler.DetectHostIP(w, r)
		// System (transactional) email — invite/verification links (Phase 5.1b)
		case r.Method == "GET" && path == "/api/settings/system-email":
			handler.GetSystemEmail(w, r)
		case r.Method == "PUT" && path == "/api/settings/system-email":
			handler.PutSystemEmail(w, r)
		case r.Method == "POST" && path == "/api/settings/system-email/test":
			handler.TestSystemEmail(w, r)
		// Backup targets
		case r.Method == "GET" && path == "/api/settings/backup-targets":
			handler.ListBackupTargets(w, r)
		case r.Method == "POST" && path == "/api/settings/backup-targets":
			handler.CreateBackupTarget(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/settings/backup-targets/"):
			handler.UpdateBackupTarget(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/settings/backup-targets/"):
			handler.DeleteBackupTarget(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/settings/backup-targets/") && hasSuffix(path, "/test"):
			handler.TestBackupTarget(w, r)
		// Docker registries
		case r.Method == "GET" && path == "/api/settings/registries":
			handler.ListRegistries(w, r)
		case r.Method == "POST" && path == "/api/settings/registries":
			handler.CreateRegistry(w, r)
		// Rigger-managed registry (image-distribution Phase 2) — exact paths,
		// matched before the generic {id} prefix cases below.
		case r.Method == "GET" && path == "/api/settings/registries/managed":
			handler.GetManagedRegistry(w, r)
		case r.Method == "POST" && path == "/api/settings/registries/managed":
			handler.ManagedRegistryAction(w, r)
		// Rigger-managed metrics TSDB (Part C — VictoriaMetrics for Rigger's own metrics).
		case r.Method == "GET" && path == "/api/settings/metrics/managed":
			handler.GetManagedMetrics(w, r)
		case r.Method == "POST" && path == "/api/settings/metrics/managed":
			handler.ManagedMetricsAction(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/settings/registries/") && hasSuffix(path, "/system"):
			handler.MarkRegistrySystem(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/settings/registries/") && !hasSuffix(path, "/test"):
			handler.UpdateRegistry(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/settings/registries/"):
			handler.DeleteRegistry(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/settings/registries/") && hasSuffix(path, "/test"):
			handler.TestRegistry(w, r)
		// Notification channels (6b)
		case r.Method == "GET" && path == "/api/settings/notification-channels":
			handler.ListNotificationChannels(w, r)
		case r.Method == "GET" && path == "/api/settings/proxy/plugins":
			handler.GetProxyPlugins(w, r)
		case r.Method == "POST" && path == "/api/settings/proxy/plugins":
			handler.SetProxyPlugins(w, r)
		case r.Method == "POST" && path == "/api/settings/notification-channels":
			handler.CreateNotificationChannel(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/settings/notification-channels/") && hasSuffix(path, "/test"):
			handler.TestNotificationChannel(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/settings/notification-channels/"):
			handler.UpdateNotificationChannel(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/settings/notification-channels/"):
			handler.DeleteNotificationChannel(w, r)
		// API keys (external /api/v1 credentials) — admin-managed.
		case r.Method == "GET" && path == "/api/settings/api-key-scopes":
			handler.GetApiKeyScopes(w, r)
		case r.Method == "GET" && path == "/api/settings/api-keys":
			handler.ListApiKeys(w, r)
		case r.Method == "POST" && path == "/api/settings/api-keys":
			handler.CreateApiKey(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/settings/api-keys/"):
			handler.UpdateApiKey(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/settings/api-keys/"):
			handler.DeleteApiKey(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))

	// Hosts (Phase 7: Multi-Host Support) — global host registry, admin only
	mux.Handle("/api/hosts", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case "GET":
			handler.ListHosts(w, r)
		case "POST":
			handler.CreateHost(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))
	mux.Handle("/api/hosts/", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		switch {
		case r.Method == "GET" && path == "/api/hosts/managed-key":
			handler.ManagedHostKey(w, r)
		case r.Method == "GET" && hasSuffix(path, "/stats"):
			handler.HostStats(w, r)
		case r.Method == "POST" && hasSuffix(path, "/test"):
			handler.TestHost(w, r)
		case r.Method == "POST" && hasSuffix(path, "/build-only"):
			handler.SetHostBuildOnly(w, r)
		case r.Method == "POST" && hasSuffix(path, "/scan"):
			handler.ScanHost(w, r)
		case r.Method == "POST" && hasSuffix(path, "/import"):
			handler.ImportHost(w, r)
		case r.Method == "PUT":
			handler.UpdateHost(w, r)
		case r.Method == "DELETE":
			handler.DeleteHost(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))

	// ── External REST API (/api/v1) — authenticated by API keys, NOT the UI's JWT.
	// Each route is wrapped in APIKeyMiddleware (resolves the key); the handlers enforce
	// the per-operation scope + project access + rate limit. See internal/apikey.
	// Public docs (no key needed — documentation): OpenAPI spec + rendered page.
	mux.HandleFunc("GET /api/v1/openapi.json", handler.OpenAPISpec)
	mux.HandleFunc("GET /api/v1/docs", handler.APIDocsPage)
	// Resource-hierarchy paths: workspaces → projects → envs → services / pipelines.
	v1 := func(fn http.HandlerFunc) http.Handler { return handler.APIKeyMiddleware(fn) }
	mux.Handle("GET /api/v1/workspaces/{workspace}/projects", v1(handler.ListProjectsV1))
	mux.Handle("GET /api/v1/workspaces/{workspace}/projects/{project}/envs/{env}/services", v1(handler.ListServicesV1))
	mux.Handle("GET /api/v1/workspaces/{workspace}/projects/{project}/envs/{env}/services/{service}/logs", v1(handler.GetServiceLogsV1))
	mux.Handle("POST /api/v1/workspaces/{workspace}/projects/{project}/envs/{env}/actions/{action}", v1(handler.RunActionV1))
	mux.Handle("GET /api/v1/workspaces/{workspace}/projects/{project}/pipelines", v1(handler.ListPipelinesV1))
	mux.Handle("POST /api/v1/workspaces/{workspace}/projects/{project}/pipelines/{id}/runs", v1(handler.RunPipelineV1))
	mux.Handle("GET /api/v1/workspaces/{workspace}/projects/{project}/pipelines/{id}/runs/{runId}", v1(handler.GetPipelineRunV1))
	mux.Handle("POST /api/v1/workspaces/{workspace}/projects/{project}/pipelines/{id}/runs/{runId}/cancel", v1(handler.CancelPipelineRunV1))

	// Migration jobs (Phase 7) — poll async workspace/env host moves
	mux.Handle("/api/migration-jobs/", authSvc.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "GET" {
			r.SetPathValue("id", pathSegment(r.URL.Path, 2))
			handler.GetMigrationJob(w, r)
			return
		}
		http.NotFound(w, r)
	})))

	// Alerts (Phase 6) — rules CRUD + events inbox, all JWT-protected
	mux.Handle("/api/alerts/", authSvc.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		switch {
		// Rules (6a)
		case r.Method == "GET" && path == "/api/alerts/rules":
			handler.ListAlertRules(w, r)
		case r.Method == "POST" && path == "/api/alerts/rules":
			handler.CreateAlertRule(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/alerts/rules/"):
			handler.UpdateAlertRule(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/alerts/rules/"):
			handler.DeleteAlertRule(w, r)
		// Events / inbox (6c) — exact paths before the generic dismiss matcher
		case r.Method == "GET" && path == "/api/alerts/summary":
			handler.AlertSummary(w, r)
		case r.Method == "GET" && path == "/api/alerts/events/unread-count":
			handler.AlertUnreadCount(w, r)
		case r.Method == "GET" && path == "/api/alerts/events":
			handler.ListAlertEvents(w, r)
		case r.Method == "POST" && path == "/api/alerts/events/dismiss-all":
			handler.DismissAllAlerts(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/alerts/events/") && hasSuffix(path, "/dismiss"):
			handler.DismissAlert(w, r)
		case r.Method == "GET" && path == "/api/alerts/meta":
			handler.AlertMeta(w, r)
		default:
			http.NotFound(w, r)
		}
	})))

	// Proxy Service — standalone reverse-proxy manager (super-admin only).
	mux.Handle("/api/proxy/", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		switch {
		case r.Method == "GET" && path == "/api/proxy/routes":
			handler.ListProxyRoutes(w, r)
		case r.Method == "POST" && path == "/api/proxy/routes":
			handler.CreateProxyRoute(w, r)
		case r.Method == "GET" && path == "/api/proxy/certs":
			handler.ListProxyCerts(w, r)
		case r.Method == "GET" && path == "/api/proxy/access-lists":
			handler.ListProxyAccessLists(w, r)
		case r.Method == "POST" && path == "/api/proxy/access-lists":
			handler.CreateProxyAccessList(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/proxy/access-lists/"):
			handler.UpdateProxyAccessList(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/proxy/access-lists/"):
			handler.DeleteProxyAccessList(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/proxy/routes/") && hasSuffix(path, "/test"):
			handler.TestProxyRoute(w, r)
		case r.Method == "PUT" && matchPrefix(path, "/api/proxy/routes/"):
			handler.UpdateProxyRoute(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/proxy/routes/"):
			handler.DeleteProxyRoute(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))

	// Housekeeping — all JWT-protected
	mux.Handle("/api/housekeeping/", authSvc.Middleware(adminOnly(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		switch {
		case r.Method == "GET"  && path == "/api/housekeeping/status":
			handler.HousekeepingStatus(w, r)
		case r.Method == "GET"  && path == "/api/housekeeping/log":
			handler.HousekeepingLog(w, r)
		// Migration leftovers (Phase 7)
		case r.Method == "GET" && path == "/api/housekeeping/migration-leftovers":
			handler.ListMigrationLeftovers(w, r)
		case r.Method == "POST" && matchPrefix(path, "/api/housekeeping/migration-leftovers/") && hasSuffix(path, "/clean"):
			handler.CleanMigrationLeftover(w, r)
		case r.Method == "DELETE" && matchPrefix(path, "/api/housekeeping/migration-leftovers/"):
			handler.DismissMigrationLeftover(w, r)
		// Docker images
		case r.Method == "GET"  && path == "/api/housekeeping/docker/images":
			handler.ListHousekeepingImages(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/dangling-images":
			handler.PruneDanglingImages(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/unused-images":
			handler.PruneUnusedImages(w, r)
		// Docker containers
		case r.Method == "GET"  && path == "/api/housekeeping/docker/containers":
			handler.ListStoppedContainers(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/containers":
			handler.PruneContainers(w, r)
		// Docker volumes
		case r.Method == "GET"  && path == "/api/housekeeping/docker/volumes":
			handler.ListDanglingVolumes(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/volumes":
			handler.PruneVolumes(w, r)
		// Docker networks & build cache
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/networks":
			handler.PruneNetworks(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/docker/prune/build-cache":
			handler.PruneBuildCache(w, r)
		// Host OS
		case r.Method == "POST" && path == "/api/housekeeping/host/apt/clean":
			handler.AptClean(w, r)
		case r.Method == "GET"  && path == "/api/housekeeping/host/journal/stats":
			handler.JournalStats(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/host/journal/vacuum":
			handler.JournalVacuum(w, r)
		case r.Method == "GET"  && path == "/api/housekeeping/host/kernels":
			handler.ListKernels(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/host/kernels/clean":
			handler.CleanKernels(w, r)
		case r.Method == "POST" && path == "/api/housekeeping/host/tmp/clean":
			handler.CleanTmp(w, r)
		default:
			http.NotFound(w, r)
		}
	}))))

	// WebSocket action endpoint — auth via token in first WS message
	mux.HandleFunc("/api/workspaces/{workspace}/projects/{name}/action", func(w http.ResponseWriter, r *http.Request) {
		handler.RunAction(w, r)
	})

	// Phase 9: deployment pipelines (project-scoped). REST CRUD + run history are
	// JWT-authed via middleware (per-project RBAC enforced in the handlers); the run
	// endpoint is a WebSocket authed by a token in its first message (like /action).
	// Release-pipeline #4: explicit env deploy-tier order (drives auto-seeded pipelines).
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/env-order", authSvc.Middleware(http.HandlerFunc(handler.GetEnvOrder)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/env-order", authSvc.Middleware(http.HandlerFunc(handler.PutEnvOrder)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/build-host", authSvc.Middleware(http.HandlerFunc(handler.GetProjectBuildHost)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/build-host", authSvc.Middleware(http.HandlerFunc(handler.SetProjectBuildHost)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/build-pipeline", authSvc.Middleware(http.HandlerFunc(handler.SetBuildPipeline)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/pipelines", authSvc.Middleware(http.HandlerFunc(handler.ListPipelines)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/suggest", authSvc.Middleware(http.HandlerFunc(handler.SuggestPipeline)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines", authSvc.Middleware(http.HandlerFunc(handler.CreatePipeline)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/pipelines/{id}", authSvc.Middleware(http.HandlerFunc(handler.UpdatePipeline)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/pipelines/{id}", authSvc.Middleware(http.HandlerFunc(handler.DeletePipeline)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/runs", authSvc.Middleware(http.HandlerFunc(handler.ListPipelineRuns)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/runs/{runId}", authSvc.Middleware(http.HandlerFunc(handler.GetPipelineRun)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/runs/{runId}/approve", authSvc.Middleware(http.HandlerFunc(handler.ApprovePipelineRun)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/runs/{runId}/reject", authSvc.Middleware(http.HandlerFunc(handler.RejectPipelineRun)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/runs/{runId}/cancel", authSvc.Middleware(http.HandlerFunc(handler.CancelPipelineRun)))
	// POST triggers a run in the background and returns its id; the UI then opens a
	// poll-based log/status view bound to that run (closeable + reopenable).
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/run", authSvc.Middleware(http.HandlerFunc(handler.StartPipelineRun)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/webhooks", authSvc.Middleware(http.HandlerFunc(handler.ListPipelineWebhooks)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/webhooks", authSvc.Middleware(http.HandlerFunc(handler.CreatePipelineWebhook)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/pipelines/{id}/webhooks/{whId}", authSvc.Middleware(http.HandlerFunc(handler.DeletePipelineWebhook)))

	// PUBLIC pipeline webhook trigger — no JWT; authed by the URL token (+ optional
	// HMAC signature). Registered as a specific pattern so it isn't shadowed.
	mux.HandleFunc("POST /api/pipelines/hooks/{token}", func(w http.ResponseWriter, r *http.Request) {
		handler.InboundWebhook(w, r)
	})

	// PUBLIC preview/PR webhook — no JWT; authed by the URL token (+ provider HMAC
	// signature). Drives the ephemeral pr{n} environment lifecycle (Phase 3).
	mux.HandleFunc("POST /api/previews/hooks/{token}", func(w http.ResponseWriter, r *http.Request) {
		handler.InboundPreviewWebhook(w, r)
	})

	// PUBLIC GitHub App manifest-flow callbacks (Phase 12) — top-level browser
	// redirects from github.com, so no JWT; bound to a one-time random `state`.
	mux.HandleFunc("GET /api/git-providers/github/callback", handler.GitHubAppCallback)
	mux.HandleFunc("GET /api/git-providers/github/setup", handler.GitHubAppSetup)

	// Phase 9e: per-env deploy history + rollback (authed; per-project RBAC inside).
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/deploy-history", authSvc.Middleware(http.HandlerFunc(handler.ListDeployHistory)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/rollback", authSvc.Middleware(http.HandlerFunc(handler.RollbackEnv)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/copy", authSvc.Middleware(http.HandlerFunc(handler.CopyEnvironment)))
	// Preview/PR environments (authed; per-project RBAC inside). The public webhook
	// receiver is registered separately above (token-authed, no JWT).
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/preview", authSvc.Middleware(http.HandlerFunc(handler.GetPreviewSettings)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/preview", authSvc.Middleware(http.HandlerFunc(handler.SetPreviewConfig)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/preview/writeback-token", authSvc.Middleware(http.HandlerFunc(handler.SetPreviewWritebackToken)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/preview/webhooks", authSvc.Middleware(http.HandlerFunc(handler.CreatePreviewWebhook)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/preview/webhooks/{id}", authSvc.Middleware(http.HandlerFunc(handler.DeletePreviewWebhook)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/preview/envs/{pr}/redeploy", authSvc.Middleware(http.HandlerFunc(handler.RedeployPreview)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/preview/envs/{pr}", authSvc.Middleware(http.HandlerFunc(handler.TeardownPreviewEnv)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/migrate-data", authSvc.Middleware(http.HandlerFunc(handler.MigrateEnvData)))
	// Replace an upload-source project's stored archive (operator+); next build re-extracts it.
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/source", authSvc.Middleware(http.HandlerFunc(handler.ReplaceSource)))
	// Build-image lifecycle (#): per-env pointer status + catch-up to latest.
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/database", authSvc.Middleware(http.HandlerFunc(handler.GetDatabaseInfo)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/schemas", authSvc.Middleware(http.HandlerFunc(handler.ListDatabaseSchemas)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/schemas", authSvc.Middleware(http.HandlerFunc(handler.CreateDatabaseSchema)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/schemas/{schema}", authSvc.Middleware(http.HandlerFunc(handler.DeleteDatabaseSchema)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/seed", authSvc.Middleware(http.HandlerFunc(handler.SeedDatabase)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/users", authSvc.Middleware(http.HandlerFunc(handler.ListDatabaseUsers)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/users", authSvc.Middleware(http.HandlerFunc(handler.CreateDatabaseUser)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/database/adminer-login", authSvc.Middleware(http.HandlerFunc(handler.AdminerLogin)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/maintenance", authSvc.Middleware(http.HandlerFunc(handler.GetMaintenance)))
	mux.Handle("PUT /api/workspaces/{workspace}/projects/{name}/envs/{env}/maintenance", authSvc.Middleware(http.HandlerFunc(handler.PutMaintenance)))
	// Managed Service Console (P4) — non-DB sidecars (redis/object-storage/mailpit) + MinIO buckets.
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/services", authSvc.Middleware(http.HandlerFunc(handler.GetServiceConsole)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/storage/buckets", authSvc.Middleware(http.HandlerFunc(handler.ListStorageBuckets)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/storage/buckets", authSvc.Middleware(http.HandlerFunc(handler.CreateStorageBucket)))
	// Env-card TLS cert status (issuer + expiry) for SSL envs — reads Traefik's ACME store.
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/cert", authSvc.Middleware(http.HandlerFunc(handler.GetCertInfo)))
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/image-status", authSvc.Middleware(http.HandlerFunc(handler.GetImageStatus)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/track-latest", authSvc.Middleware(http.HandlerFunc(handler.TrackLatest)))
	// Custom domains (Render-style): attach + verify external domains for an env.
	mux.Handle("GET /api/workspaces/{workspace}/projects/{name}/envs/{env}/domains", authSvc.Middleware(http.HandlerFunc(handler.ListCustomDomains)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/domains", authSvc.Middleware(http.HandlerFunc(handler.CreateCustomDomain)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/domains/{id}/verify", authSvc.Middleware(http.HandlerFunc(handler.VerifyCustomDomain)))
	mux.Handle("POST /api/workspaces/{workspace}/projects/{name}/envs/{env}/domains/{id}/primary", authSvc.Middleware(http.HandlerFunc(handler.SetPrimaryCustomDomain)))
	mux.Handle("DELETE /api/workspaces/{workspace}/projects/{name}/envs/{env}/domains/{id}", authSvc.Middleware(http.HandlerFunc(handler.DeleteCustomDomain)))

	// Phase 2b: repo scanner — clone + static-detect a stack into a draft service graph.
	mux.Handle("POST /api/scan-repo", authSvc.Middleware(http.HandlerFunc(handler.ScanRepo)))
	mux.Handle("POST /api/parse-compose", authSvc.Middleware(http.HandlerFunc(handler.ParseCompose)))
	// Upload-source: extract an uploaded archive + detect into a draft (Custom application).
	mux.Handle("POST /api/upload-source", authSvc.Middleware(http.HandlerFunc(handler.UploadSource)))
	// Stack blueprints for the no-repo "start from a template" picker.
	mux.Handle("GET /api/blueprints", authSvc.Middleware(http.HandlerFunc(handler.Blueprints)))
	// Managed database catalog (engines + selectable versions) for the DB picker.
	mux.Handle("GET /api/databases", authSvc.Middleware(http.HandlerFunc(handler.Databases)))

	// WebSocket terminal — interactive shell into a container
	mux.HandleFunc("/api/workspaces/{workspace}/projects/{name}/envs/{env}/terminal", func(w http.ResponseWriter, r *http.Request) {
		handler.Terminal(w, r)
	})

	// Public maintenance page: per-env Traefik routers rewrite an env's host to this
	// path when maintenance is on. Unauthenticated by design; returns 503. Registered
	// before the SPA catch-all so it isn't swallowed by index.html.
	mux.HandleFunc("GET /maintenance/{workspace}/{name}/{env}", handler.MaintenancePage)

	// Proxy Service catch-all status responder (default route in 404/403/close mode).
	// Unauthenticated by design; registered before the SPA catch-all.
	mux.HandleFunc("/__proxydefault/{mode}", handler.ProxyDefault)

	// ── Static frontend (SPA) ────────────────────────────────────────────────
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		log.Fatalf("embed fs: %v", err)
	}
	spa := spaHandler{fs: http.FS(distFS)}
	mux.Handle("/", spa)

	// ── Start server ──────────────────────────────────────────────────────────
	log.Printf("Rigger UI listening on %s", cfg.ListenAddr)
	log.Printf("Toolkit root : %s", cfg.ToolkitRoot)
	log.Printf("Workspaces   : %s", cfg.WorkspacesDir)

	if err := http.ListenAndServe(cfg.ListenAddr, mux); err != nil {
		log.Fatalf("server: %v", err)
	}
}

// spaHandler serves the React SPA: known assets are served directly;
// everything else falls back to index.html for client-side routing.
type spaHandler struct{ fs http.FileSystem }

func (s spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	f, err := s.fs.Open(r.URL.Path)
	if err != nil {
		// Serve index.html for any unknown path (client-side routing)
		r.URL.Path = "/"
		http.FileServer(s.fs).ServeHTTP(w, r)
		return
	}
	f.Close()
	http.FileServer(s.fs).ServeHTTP(w, r)
}

// ── URL helpers ───────────────────────────────────────────────────────────────

func matchPrefix(path, prefix string) bool {
	return len(path) >= len(prefix) && path[:len(prefix)] == prefix
}

func hasSuffix(path, suffix string) bool {
	return len(path) >= len(suffix) && path[len(path)-len(suffix):] == suffix
}

func pathSegment(path string, n int) string {
	parts := splitPath(path)
	if n < len(parts) {
		return parts[n]
	}
	return ""
}

// removeRunSh deletes the generated run.sh from every workspace. Commands now run
// natively in Go (Phase 6.5 finish); run.sh is a stale generated artifact, so
// removing it is safe (no user data). Idempotent — absent files are ignored.
func removeRunSh(workspacesDir string) {
	entries, err := os.ReadDir(workspacesDir)
	if err != nil {
		return
	}
	removed := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		runSh := filepath.Join(workspacesDir, e.Name(), "run.sh")
		if err := os.Remove(runSh); err == nil {
			removed++
		}
	}
	if removed > 0 {
		log.Printf("removeRunSh: removed stale run.sh from %d workspace(s)", removed)
	}
}

func splitPath(path string) []string {
	var parts []string
	cur := ""
	for _, c := range path {
		if c == '/' {
			if cur != "" {
				parts = append(parts, cur)
				cur = ""
			}
		} else {
			cur += string(c)
		}
	}
	if cur != "" {
		parts = append(parts, cur)
	}
	return parts
}
