// Package gateway implements model #3 routing: when a workload runs on a PRIVATE
// remote host (only the control plane is exposed on :80/:443), the control-plane
// Traefik must front it. This writes a Traefik file-provider fragment on the control
// plane — a router matching the app's public Host that forwards to the remote host's
// edge Traefik on :80 (preserving the Host header so the remote edge routes the final
// hop to the app container). It reuses the same /dynamic file-provider mechanism the
// Proxy Service uses; fragments are named gateway-*.yml so the Proxy Service's
// proxy-*.yml rebuild never touches them. See host-reachability-routing.
package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// id builds a stable, filesystem/Traefik-safe identifier for an env's gateway route.
func id(workspace, project, env string) string {
	repl := func(s string) string {
		var b strings.Builder
		for _, r := range s {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
				b.WriteRune(r)
			} else {
				b.WriteByte('-')
			}
		}
		return b.String()
	}
	return "gw-" + repl(workspace) + "-" + repl(project) + "-" + repl(env)
}

// FragPath is the file-provider fragment path for an env's gateway route.
func FragPath(dir, workspace, project, env string) string {
	return filepath.Join(dir, id(workspace, project, env)+".yml")
}

// Route describes one gateway forward-route.
type Route struct {
	PublicHost  string   // the app's public hostname (Host rule), e.g. app.example.com
	UpstreamURL string   // where to forward, e.g. http://10.10.10.55:80 (the remote edge)
	TLS         bool     // terminate TLS here (base-domain HTTPS) vs plain HTTP (magic-DNS)
	Middlewares []string // extra @file middleware refs (e.g. rigger-loading@file)
}

// Write (re)writes the env's gateway fragment. Best-effort caller ensures dir exists.
func Write(dir, workspace, project, env string, r Route) error {
	if r.PublicHost == "" || r.UpstreamURL == "" {
		return fmt.Errorf("gateway: public host and upstream are required")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("gateway: ensure %s: %w", dir, err)
	}
	rid := id(workspace, project, env)
	entry := "web"
	if r.TLS {
		entry = "websecure"
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by Rigger — gateway route to a private host. Do not edit.\n")
	fmt.Fprintf(&b, "# %s/%s/%s → %s\n", workspace, project, env, r.UpstreamURL)
	b.WriteString("http:\n  routers:\n")
	fmt.Fprintf(&b, "    %s:\n", rid)
	fmt.Fprintf(&b, "      rule: \"Host(`%s`)\"\n", r.PublicHost)
	fmt.Fprintf(&b, "      entryPoints:\n        - %s\n", entry)
	fmt.Fprintf(&b, "      service: %s\n", rid)
	if len(r.Middlewares) > 0 {
		b.WriteString("      middlewares:\n")
		for _, m := range r.Middlewares {
			fmt.Fprintf(&b, "        - %s\n", m)
		}
	}
	if r.TLS {
		// Serve the control plane's existing cert for this SNI (the workspace's wildcard
		// {*.base} issued when its base domain was configured). tls:{} matches by SNI.
		b.WriteString("      tls: {}\n")
	}
	b.WriteString("  services:\n")
	fmt.Fprintf(&b, "    %s:\n", rid)
	b.WriteString("      loadBalancer:\n")
	// Preserve the Host header so the remote edge Traefik matches the app router there.
	b.WriteString("        passHostHeader: true\n")
	b.WriteString("        servers:\n")
	fmt.Fprintf(&b, "          - url: %q\n", r.UpstreamURL)

	if err := os.WriteFile(FragPath(dir, workspace, project, env), []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("gateway: write fragment: %w", err)
	}
	return nil
}

// Remove deletes the env's gateway fragment (no error if it never existed).
func Remove(dir, workspace, project, env string) error {
	if err := os.Remove(FragPath(dir, workspace, project, env)); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
